#!/bin/sh

# Barebox автоматически заполняет переменные global.bootsource (например, "mmc") 
# и global.bootsource_instance (0 для eMMC, 1 для SD согласно вашему devinfo)

CURRENT_MMC="mmc${global.bootsource_instance}"

mkdir -p /mnt/rootfs_a
mkdir -p /mnt/rootfs_b

# Динамически монтируем разделы текущего активного накопителя
mount /dev/${CURRENT_MMC}.rootfs_a /mnt/rootfs_a > /dev/null 2>&1
mount /dev/${CURRENT_MMC}.rootfs_b /mnt/rootfs_b > /dev/null 2>&1

# Далее bootchooser сам выберет, какой из смонтированных путей запустить

exit 0

if [ -f /mnt/mmc1.2/boot/Image.gz ]; then
	echo "Booting from SD"

	DTB=/mnt/mmc1.2/boot/rk3568-diasom-som-evb.dtb

	global.bootm.image=/mnt/mmc1.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk1p3 ro rootdelay=3"
elif [ -f /mnt/mmc0.2/boot/Image.gz ]; then
	echo "Booting from eMMC"

	DTB=/mnt/mmc0.2/boot/rk3568-diasom-som-evb.dtb

	global.bootm.image=/mnt/mmc0.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk0p3 ro rootdelay=3"
else
	echo "Boot image not found!"
	exit 1
fi

if [ -f $DTB ]; then
	echo "Using external devicetree blob from $DTB"
	global.bootm.oftree=$DTB
else
	echo "Using internal devicetree blob"
fi

exit 0
