#!/bin/sh

# Автоматически собираем имя текущего загрузочного диска (mmc0 или mmc1)
CURRENT_DEV="mmc${global.bootsource_instance}"

mkdir -p /mnt/line_a
# Монтируем rootfs_a именно с того накопителя, с которого плата сейчас работает
mount /dev/${CURRENT_DEV}.rootfs_a /mnt/line_a > /dev/null 2>&1

global.bootm.image=/mnt/line_a/boot/Image.gz
global.bootm.oftree=/mnt/line_a/boot/rk3568-diasom-som-evb.dtb
global.linux.bootargs.dyn.root="root=PARTUUID=b921b045-1df0-41c3-af44-4c6f280d3fae ro rootwait"

exit 0

if [ -f /mnt/mmc1.2/boot/Image.gz ]; then
	echo "Booting from SD"

	DTB=/mnt/mmc1.2/boot/rk3568-diasom-som-evb.dtb

	global.bootm.image=/mnt/mmc1.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk1p3 ro rootdelay=3"
elif [ -f /mnt/mmc0.2/boot/Image.gz ]; then
	echo "Booting from eMMC"

	DTB=/mnt/mmc0.2/boot/rk3568-diasom-som-evb.dtb

	global.bootm.image=/mnt/mmc0.2/boot/Image.gz
	global.linux.bootargs.dyn.root="root=/dev/mmcblk0p3 ro rootdelay=3"
else
	echo "Boot image not found!"
	exit 1
fi

if [ -f $DTB ]; then
	echo "Using external devicetree blob from $DTB"
	global.bootm.oftree=$DTB
else
	echo "Using internal devicetree blob"
fi

exit 0
