#!/bin/sh

CURRENT_DEV="mmc${global.bootsource_instance}"

mkdir -p /mnt/rootfs_a
mount /dev/${CURRENT_DEV}.rootfs_a /mnt/rootfs_a

global.bootm.image=/mnt/rootfs_a/boot/Image.gz
# Barebox сам передаст ядру внутреннее дерево устройств (Internal DTB)
global.linux.bootargs.dyn.root="root=PARTUUID=b921b045-1df0-41c3-af44-4c6f280d3fae rw rootwait"
