#!/bin/sh

CURRENT_DEV="mmc${global.bootsource_instance}"

mkdir -p /mnt/rootfs_b
mount /dev/${CURRENT_DEV}.rootfs_b /mnt/rootfs_b > /dev/null 2>&1

global.bootm.image=/mnt/rootfs_b/boot/Image.gz
global.bootm.oftree=/mnt/rootfs_b/boot/rk3568-diasom-som-evb.dtb
global.linux.bootargs.dyn.root="root=PARTUUID=b921b045-1df0-41c3-af44-4c6f280d3fae rw rootwait"
