#!/bin/sh

# Автоматически определяем текущий диск (mmc0 или mmc1), с которого запустился Barebox
CURRENT_DEV="mmc${global.bootsource_instance}"

mkdir -p /mnt/rootfs_a
mount /dev/${CURRENT_DEV}.rootfs_a /mnt/rootfs_a > /dev/null 2>&1

# Прописываем пути к ядру и DTB внутри вашего rootfs_a
global.bootm.image=/mnt/rootfs_a/boot/Image.gz
global.bootm.oftree=/mnt/rootfs_a/boot/rk3568-diasom-som-evb.dtb
global.linux.bootargs.dyn.root="root=PARTUUID=b921b045-1df0-41c3-af44-4c6f280d3fae rw rootwait"
